on:
  push:
    branches: [main]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Execute unit tests
        run: yarn test

      - name: Run Drizzle migrate
        run: |
          yarn db:push
        env:
          DATABASE_URL: "${{ secrets.DATABASE_URL }}"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          AUTH_GITHUB_ID: "${{ secrets.AUTH_GITHUB_ID }}"
          AUTH_GITHUB_SECRET: "${{ secrets.AUTH_GITHUB_SECRET }}"
          AUTH_SECRET: "${{ secrets.AUTH_SECRET }}"
          DATABASE_URL: "${{ secrets.DATABASE_URL }}"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
