on:
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
      checks: 'write'
      pull-requests: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Execute unit tests
        run: yarn test

      - name: Get PR sha
        id: get_pull_request_sha
        run: |
          pull_request_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH" | cut -c1-8)
          echo "pull_request_sha=${pull_request_sha}" >> $GITHUB_OUTPUT
          echo $pull_request_sha

      - name: Neon Database Create Branch Action
        uses: neondatabase/create-branch-action@v5
        id: create_branch
        if: github.actor != 'dependabot[bot]'
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          parent: dev
          branch_name: ${{steps.get_pull_request_sha.outputs.pull_request_sha}}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PG_USERNAME }}

      - name: Build backend
        run: yarn build
        env:
          AUTH_GITHUB_ID: '${{ secrets.AUTH_GITHUB_ID }}'
          AUTH_GITHUB_SECRET: '${{ secrets.AUTH_GITHUB_SECRET }}'
          AUTH_SECRET: '${{ secrets.AUTH_SECRET }}'
          DATABASE_URL: '${{ steps.create_branch.outputs.db_url_with_pooler }}/neondb?pgbouncer=true&connect_timeout=10&sslmode=require'

      - name: Run Drizzle migrate
        if: github.actor != 'dependabot[bot]'
        run: |
          yarn db:push
        env:
          DATABASE_URL: '${{ steps.create_branch.outputs.db_url_with_pooler }}/neondb?pgbouncer=true&connect_timeout=10&sslmode=require'
